NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import Post, PostDetail, NewsCreate, ArticleCreate, PostUpdate, PostDelete
from django.views.decorators.cache import cache_page

urlpatterns = [
   path('i18n/', include('django.conf.urls.i18n')),
   path('admin/', admin.site.urls),
   path('news/', include('news.urls')),
   path("accounts/", include("allauth.urls")),
   path('', include('board.urls')),
   path('', Post),
   path('<int:pk>/', cache_page(60 * 10)
   (PostDelete.as_view()), name='post_detail'),
   path('create/', NewsCreate.as_view(), name='post_create'),
   path('create/', ArticleCreate.as_view(), name='post_create'),
   path('<int:pk>/update', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete', PostDelete.as_view(), name='post_delete'),
]

news/urls.py
from django.urls import path, include
from .views import (
    PostList, PostDetail, NewsCreate, ArticleCreate, PostUpdate, PostDelete, PostSearch, subscriptions, PostViewSet
)
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'news', PostViewSet, basename='news')
router.register(r'articles', PostViewSet, basename='articles')

urlpatterns = [
    path('', (PostList.as_view()), name='news_list'),
    path('<int:id>/', (PostDetail.as_view()), name='news_detail'),
    path('articles/create/', ArticleCreate.as_view(), name='article_create'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('articles/<int:id>/edit/', PostUpdate.as_view(), name='article_edit'),
    path('news/<int:id>/edit/', PostUpdate.as_view(), name='news_edit'),
    path('articles/<int:id>/delete/', PostDelete.as_view(), name='article_delete'),
    path('news/<int:id>/delete/', PostDelete.as_view(), name='news_delete'),
    path('search/', PostSearch.as_view(), name='post_search'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('', include(router.urls)),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.validators import MinValueValidator
from django.core.cache import cache
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = postRat.get('postRating') or 0

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = commentRat.get('commentRating') or 0

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True, help_text=_('category name'))

    def __str__(self):
        return self.name


class MyModel(models.Model):
    name = models.CharField(max_length=100)
    kind = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='kinds',
        verbose_name=pgettext_lazy('help text for MyModel model', 'This is the help text'),
    )

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)


    NEWS = 'NEWS'
    ARTICLE = 'ARTICLE'
    POST_TYPES = [
        ('NEWS', 'Новость'),
        ('ARTICLE', 'Статья'),
    ]
    categoryType = models.CharField(max_length=7, choices=POST_TYPES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    text = models.TextField()
    title = models.CharField(max_length=128)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return f'{self.title[:123]} ... Рейтинг: {self.rating}'

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        cache.delete(f'product-{self.id}')


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

class Subscriber(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post

class PostForm(forms.ModelForm):
    text = forms.CharField(min_length=20, widget=forms.Textarea)

    class Meta:
        model = Post
        fields = [
            'author',
            'title',
            'categoryType',
            'text',
            'postCategory',
        ]
        widgets = {
            'postCategory': forms.CheckboxSelectMultiple,
        }

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        text = cleaned_data.get("text")

        if title and text and title.lower() == text.lower():
            raise ValidationError(
                "Текст не должен быть идентичен заголовку."
            )

        return cleaned_data

news/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from .models import Post, Subscription, Category, MyModel
from .filters import PostFilter
from .forms import PostForm

from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect

from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.views import View
from django.http import HttpResponse
from django.http.response import HttpResponse
from django.utils.translation import gettext as _
from django.utils import timezone
from django.shortcuts import redirect, render
from datetime import datetime
import pytz
from rest_framework import viewsets, permissions
from .serializers import PostSerializer


class PostDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'id'

    def get_object(self, *args, **kwargs):
        obj = cache.get(f'post-{self.kwargs["id"]}', None)

        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["id"]}', obj)
        return obj


class NewsCreate(CreateView, PermissionRequiredMixin):
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'
    raise_exception = True

    def form_valid(self, form):
        news = form.save(commit=False)
        news.categoryType = 'NEWS'
        return super().form_valid(form)


class ArticleCreate(CreateView, PermissionRequiredMixin):
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'
    raise_exception = True

    def form_valid(self, form):
        article = form.save(commit=False)
        article.categoryType = 'ARTICLE'
        return super().form_valid(form)


class PostUpdate(UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'
    pk_url_kwarg = 'id'


class PostDelete(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')
    pk_url_kwarg = 'id'


class FilteredListViewMixin:
    filter_class = None

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.filter_class:
            self.filterset = self.filter_class(self.request.GET, queryset)
            return self.filterset.qs
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = getattr(self, 'filterset', None)
        return context


class PostList(FilteredListViewMixin, ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 10
    filter_class = PostFilter


class PostSearch(FilteredListViewMixin, ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'news_search.html'
    context_object_name = 'search_results'
    paginate_by = 10
    filter_class = PostFilter


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscription.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscription.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscription.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')
    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions},
    )


class Index(View):
    def get(self, request):
        # .  Translators: This message appears on the home page only
        models = MyModel.objects.all()

        context = {
            'models': models,
            'current_time': timezone.localtime(timezone.now()),
            'timezones': pytz.common_timezones  # добавляем в контекст все доступные часовые пояса
        }

        return HttpResponse(render(request, 'index.html', context))

    #  по пост-запросу будем добавлять в сессию часовой пояс, который и будет обрабатываться написанным нами ранее middleware
    def post(self, request):
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')

class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get_permissions(self):
        if self.request.method in permissions.SAFE_METHODS:  # GET, HEAD, OPTIONS
            return [permissions.AllowAny()]
        return [permissions.IsAuthenticated()]

@cache_page(60 * 15)
def my_view(request):
    ...

templates/new.html
{% extends 'flatpages/default.html' %}
{% block title %}
Article
{% endblock title %}

{% block content %}
{% trans
<h1>{{ new.title }}</h1>
<p>Date: {{ new.dateCreation|date:'d.m.Y' }}</p>
<p>Author: {{ new.author.authorUser.username }}</p>
<p>Category: {{ new.get_categoryType_display }}</p>
<p>{{ new.text }}</p>
%}!

{% endblock content %}

templates/news.html
{% extends 'flatpages/default.html' %}
{% load cens_filter %}
{% load i18n %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>All news</h1>
<h3>{{ time_now|date:'M d Y' }}</h3>

<p>Total news: {{ news|length }}</p>

<ul>
    {% for new in news %}
    <li>
        <strong>{{ new.title|censor }}</strong> - {{ new.dateCreation|date:"d.m.Y" }}
        <p>{{ new.text|truncatewords:20 }}</p>
        <a href="{% url 'news_detail' id=new.id %}">Read more</a>

        {% if perms.news.delete_news %}
        <a href="{% url 'news_delete' id=new.id %}">Удалить</a>
        {% endif %}

        {% if perms.news.change_news %}
        <a href="{% url 'news_edit' id=new.id %}">Редактировать</a>
        {% endif %}
    </li>
    {% endfor %}
</ul>

{% if not news %}
<h2>Нет новостей!</h2>
{% endif %}

{% endblock content %}

templates/news_detail.html
{% extends 'flatpages/default.html' %}

{% block title %}
{{new.title}}
{% endblock title %}

{% block content %}
<h1>{{ new.title }}</h1>
<p>Published on: {{ new}}</p>
<p>Published on: {{ new.dateCreation|date:'d.m.Y' }}</p>
<div>
    <p> {{new.text}}</p>
</div>
{% endblock content %}

templates/news_search.html
{% extends 'flatpages/default.html' %}
{% block content %}
  <h2>Поиск новостей</h2>
  <form method="get">
      {{ filterset.form.as_p }}
      <button type="submit">Поиск</button>
  </form>

  <h3>Результаты поиска:</h3>
  <ul>
      {% for post in search_results %}
          <li>
              <a href="{% url 'news_detail' post.id %}">{{ post.title }}</a> - {{ post.dateCreation }}
          </li>
      {% empty %}
          <p>Нет новостей, соответствующих критериям поиска.</p>
      {% endfor %}
  </ul>
{% endblock %}

templates/post_delete.html
{% extends 'flatpages/default.html' %}
{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

templates/post_detail.html
{% extends 'flatpages/default.html' %}
{% block title %}
{{post.title}}
{% endblock title %}

{% block content %}
<h1>{{ post.title }}</h1>
<p>Published on: {{ post.dateCreation|date:'d.m.Y' }}</p>
<div>
    <p> {{post.text}}</p>
</div>
{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}
{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}